# [Tidyverse_Cheat_Sheet](https://res.cloudinary.com/dyd911kmh/image/upload/v1676302697/Marketing/Blog/Tidyverse_Cheat_Sheet.pdf)

# Piping data
# %>% : this is a pipe. It will pipe whatever data comes before the pipe into what comes after the pipe. 

# filter function
# filter() : Use filter to filter on data. You can create a subset of a dataset by filtering on it. 
# i.e. : 
# gapminder %>% filter(year == "2007"); This will filter all the gapminder data to show only the data for which the year was 2007.

# arrange function
# arrange() : tell it what column you want to arrange by; arrange will sort ascending by default
# Example: 
# library(gapminder)
# library(dplyr)

# Sort in ascending order of lifeExp
# gapminder %>%
#     arrange(lifeExp)

  
# Sort in descending order of lifeExp
# gapminder %>%
#     arrange(desc(lifeExp))

# descending function
# desc() : used to sort in descending order; 

# Mutate function
# mutate() : adds a column to your data; syntax is mutate(column_to_change_or_add = operation_to_change_it_to)
# note that changing the data using mutate does not change the original dataset when a pipe is used. 

# Plotting
# ggplot() : plot a scatterplot with ggplot; import the library "ggplot2"; 
# plot with the example following example: 
# ggplot(data, aes(x = pop, y = gdpPercap)) + geom_point()
# The example above will plot the data give as data. aes will create an asthetic mapping of x & y data points, and geom_point will add geometric style points to the graph
# See the full example below: 
# library(gapminder)
# library(dplyr)
# library(ggplot2)
#
# gapminder_1952 <- gapminder %>%
#  filter(year == 1952)
#
## Change to put pop on the x-axis and gdpPercap on the y-axis
# ggplot(gapminder_1952, aes(x = pop, y = gdpPercap)) +
# geom_point() 

# scale_x_log10():
# Change the x-axis to be logarithmic 
# ggplot(gapminder_1952, aes(x = pop, y = gdpPercap)) +
# geom_point() + scale_x_log10()

# scale_y_log10():
# Change the x-axis to be logarithmic 
# ggplot(gapminder_1952, aes(x = pop, y = gdpPercap)) +
# geom_point() + scale_x_log10()

# to add color
# To add color, add color inside the aes function:
# ggplot(gapminder_1952, aes(x = pop, y = gdpPercap, color = continent))

# to assign size
# To change size, add size inside the aes function:
# ggplot(gapminder_1952, aes(x = pop, y = gdpPercap, color = continent, size = gdpPercap))

# To ensure the graph includes 0 on the y axis:
# expand_limits(y=0)

# To create a scatter plot
# geom_point(): add after the ggplot to create a scatterplot

# To create a line graph
# geom_line(): add this after the ggplot to create a line graph

# To create a bar plot
# geom_col(): 

# To create a histogram
# geom_histogram() : This function will create a histogram. The width of each column of the histogram can be altered by modifying the variable "bins";
# Example:
# library(gapminder)
# library(dplyr)
# library(ggplot2)
# 
# gapminder_1952 <- gapminder %>%
#   filter(year == 1952)
# 
# # Create a histogram of population (pop), with x on a log scale
# ggplot(gapminder_1952, aes(x = pop)) + geom_histogram(bins = 50) + scale_x_log10()

# To create a boxplot
# geom_boxplot(): This function will create a boxplot. 
# Example: 
# library(gapminder)
# library(dplyr)
# library(ggplot2)
# 
# gapminder_1952 <- gapminder %>%
#   filter(year == 1952)
# 
# # Create a boxplot comparing gdpPercap among continents
# ggplot(gapminder_1952, aes(x = continent, y = gdpPercap)) + geom_boxplot() + scale_y_log10()

# Add a title to the graph
# ggtitle("Your title here")

# Faceting
# face_wrap():
# faceting will separate your plot into subplots
# first write your ggplot function then add the faceting on the same line
# ... + face_wrap(~ continent)
# in the example above, ~ means "with respect to"

# Verbs()

# Summarize
# summarize(): summarize data using syntax (data_summary_name = foo(data_to_summarize))
# it is possible to summarize multiple variables at once
# Example: 
# library(gapminder)
# library(dplyr)

# Filter for 1957 then summarize the median life expectancy and the maximum GDP per capita
# gapminder %>%
#     filter(year == 1957) %>%
#     summarize(medianLifeExp = median(lifeExp), maxGdpPercap = max(gdpPercap))

# Median
# median() : find the median of the data 

# Max
# max(): find the max of the data

# Groupby
# group_by() : group the data by a column  

