# Introduction to R: Notes on the introduction, vectors, matrices, & factors

# Add your code snippets here
# Comments
my_variable <- 5
my_character <- "character"
my_logical <- TRUE

# Print the data type
class(my_variable)
class(my_character)
class(my_logical)

# create a vector
numeric_vector <- c(1,2,3)
character_vector <- c("a","b","c")
boolean_vector <- c(TRUE,FALSE, TRUE)

# Print the vectors
numeric_vector
character_vector
boolean_vector

# naming elements of a vector
names(character_vector) <- c("first character", "second_character", "3rd Character")

# Print the character vector named "first character"
character_vector["first character"]

# Print all the named elements in the character vector
names(character_vector)

# set the names vector using another vector
character_vector_names <- c("first char", "second char", "third char")
names(character_vector) <- character_vector_names

# print the new names of the character_vector
names(character_vector)

# Addition of vectors
A_vector <- c(1,2,3)
B_vector <- c(2,3,4)

total_vector_sum <- A_vector + B_vector
total_vector_sum

# There is a sum function
sum_of_A_Vector <- sum(A_vector)
sum_of_B_Vector <- sum(B_vector)
total_vector_sum <- sum_of_A_Vector + sum_of_B_Vector
total_vector_sum

# > can be used for comparison
sum_of_A_Vector
sum_of_B_Vector
sum_of_A_Vector > sum_of_B_Vector

# R implements 1 based indexing
A_vector[1]

# R implements named element indexing
names(A_vector) <- c("1st","2nd","3rd")
A_vector["3rd"]

# Selecting multiple elements in a vector
A_vector[c(1,3)]

A_vector[c(1,2,3)]

# Selecting multiple elements using the colon notation 
A_vector[1:3] # This will select elements 1 & 2 & 3

# Index by name
A_vector[c("1st","2nd","3rd")]

# You can compare on vectors
greater_than_two <- A_vector[1:3] > 2

# Use booleans to select elements of a vector
A_vector[greater_than_two]

# Matrices

# Construct a matrix with 3 rows that contains the numbers 1 up to 9
named_matrix = matrix(1:9, byrow = TRUE, nrow = 3)


# Naming the column & rows of a matrix
colnames(named_matrix) <- c("col1", "col2","col3")
rownames(named_matrix) <- c("row1", "row2","row3")
named_matrix

# Calculating the row sums using rowSums()
sum_of_rows_vector <- rowSums(named_matrix)
sum_of_rows_vector

# Add 1 or more columns to a matrix using cbind
big_matrix <- cbind(named_matrix, sum_of_rows_vector)
big_matrix

# To check out the contents of a workspace
ls()

# Add 1 or more rows to a matrix using rbind
new_row <- c(9,0,1)
sum_of_new_row <- sum(new_row)
new_row <- c(new_row, sum_of_new_row)
new_row
larger_big_matrix <- rbind(big_matrix, new_row)
larger_big_matrix

# using colSums to sum the columns
column_sums <- colSums(larger_big_matrix)
largest_matrix <- rbind(larger_big_matrix, column_sums)
largest_matrix

# Selecting columns & rows in a matrix

print("Selecting all rows in the 1st column of the matrix")
largest_matrix[,1] # all rows, column 1

print("Selecting all columns in the 1st row of the matrix")
largest_matrix[1,] # row 1, all columns

print("Selecting the first two columns in the 1st row of the matrix")
largest_matrix[1,1:2]

# Arithmetic on matrices
print("using operators on matrices performs element-wise operations on the matrix")
largest_matrix_divided_by_5 <- largest_matrix / 5
largest_matrix_divided_by_5

# Taking the dot product of two matrices
dot_product <- largest_matrix * largest_matrix_divided_by_5
print("dot_product:")
dot_product

# factors will identify the atomic types in an array
sex_vector <- c("Male","Female","Female","Male","Male")
factor_sex_vector <- factor(sex_vector)
factor_sex_vector

# Nominal Vs. Ordinal categorical variables
print("Nominal categorical variables have no order. Animals are an example:")
animals_vector <- c("Elephant", "Giraffe", "Donkey", "Horse")
factor_animals_vector <- factor(animals_vector)
factor_animals_vector

# Temperature is an example of Ordinal categorical variables
temperature_vector <- c("High","Low","High","Low","Medium")
factor_temperature_vector <- factor(temperature_vector)
factor_temperature_vector

# Assigning levels to factor vectors:
# A factor vector with abbreviations can have the factor levels explicitly set
survey_vector <- c("M","F","F","M","M")
factor_survey_vector <- factor(survey_vector)

print("Before assigning the factor levels, they are identified by M & F")
factor_survey_vector

print("After explicit assignment of the factor levels, the levels are fully described")
levels(factor_survey_vector) <- c("Female", "Male")
factor_survey_vector

# Summary
print("Use summary() to show the contents of a variable:")
summary(factor_survey_vector)

# Explicitly creating levels so that they may be ordered: 
speed_vector <- c("medium", "slow", "slow", "medium", "fast")
factor_speed_vector <- factor(speed_vector, ordered=TRUE, levels = c("slow","medium","fast"))

factor_speed_vector
summary_factor_speed_vector

# Dataframes

# The head() method will show the first observations of a dataframe.
# The tail() method will show the last observations of a dataframe.
# str() will show you the structure of your dataframe where each column is an observation and each row is a variable
# str will show you the total number of observations, variables, a full list of the variable names, the data type of each variable, & the first observations

# Creating datafames
# The function data.frame creates a dataframe. Pass an arbitrary number of vectors into the data.frame() to create the dataframe where each column is a vector and each row is an observation in that vector

# The head() method will show the first observations of a dataframe.
# The tail() method will show the last observations of a dataframe.
# str() will show you the structure of your dataframe where each column is an observation and each row is a variable
# str will show you the total number of observations, variables, a full list of the variable names, the data type of each variable, & the first observations

# Creating dataframes
# The function data.frame creates a dataframe. Pass an arbitrary number of vectors into the data.frame() to create the dataframe where each column is a vector and each row is an observation in that vector

# Selecting values in a dataframe
# select the values in a dataframe by selecting the values in a column: eg planets_df[1:5, "diameter"] where "diameter" is the column name.
# To select all the rows of a column, a.k.a. variable, in a dataframe, use the dollar sign shortcut as in: planets_df$diameter

# Subset: to show a subset of a dataset, use the subsets() method. subset(planets_df, subset = diameter < 1)

# Ordering:
# The order function will give you a ranked position of each element when it is applied on a variable, such as a vector.
# E.G. positions <-  order(planets_df$diameter)
# planets_df[positions,]

     # name               type diameter rotation rings
# 1 Mercury Terrestrial planet    0.382    58.64 FALSE
# 4    Mars Terrestrial planet    0.532     1.03 FALSE
# 2   Venus Terrestrial planet    0.949  -243.02 FALSE
# 3   Earth Terrestrial planet    1.000     1.00 FALSE
# 8 Neptune          Gas giant    3.883     0.67  TRUE
# 7  Uranus          Gas giant    4.007    -0.72  TRUE
# 6  Saturn          Gas giant    9.449     0.43  TRUE
# 5 Jupiter          Gas giant   11.209     0.41  TRUE

# R datatypes:
# There are lists, vectors, matrices, DataFrames

# Lists()
# Lists can store booleans, numeric, & characters all in the same object
# To create a list, use the list() function
# Name your lists with assignment: my_list <- list(name1 = your_comp, name2 = your_comp2)
# Name your lists using names(): my_list <- list(your_comp1, your_comp2); names(my_list) <- c("name1","name2")
# After naming a list, dereference using the name: my_list$name1
# Again, lists use naming first, then variable assignment; E.G. list(moviename=mov, actors = act, reviews = rev) where data is stored in mov, act, & rev and the names are moviename, actors, & reviews

# Dereferencing lists: 
# use [[]] do dereference components of lists; follow with [] to dereference individual elements in a list component; E.G. shining_list[["actors"]][1] results in "Jack Nicholson"

# Equality
# In R booleans, strings, and numbers can be compared. 
# Operators: 
# == 
# !=
# < 
# >
# Vector to vector comparison is possible.
# 
# Comparison of logicals
TRUE == FALSE # FALSE is not equal to TRUE

# Comparison of numerics
-6 * 14 != 17 - 101 # This results in FALSE because they are both equal

# Comparison of character strings
"useR" == "user" # This results in FALSE

# Compare a logical with a numeric
TRUE == 1 # This results in TRUE

# R Logical operators
# & is a logical AND
# | is a logical OR
# ! is a logical not

# && returns logical result of the first element of each element whereas & performs the logical result on each element

# In order to compare ranges of elements, compare using the following notation:
# 3 < x | x < 10 
# The equation above will compare if x is between 3 and 10


# If condition
# If-else syntax:
# if (statement) { } else if (condition) { } else { }

# While loops
# while (condition) { code }
# breaks will exit the while loop completely.

# For loops
# *** Remember the () are necessary as syntax in R
# for (p in primes) { print(p)} # this will print the element in primes
# for (i in 1:length(primes)) { print(primes[[i]])} # this will print the element in primes
# using "break" will exit the for or while loop completely
# using "next" will continue looping through the for loop, but will discontinue the current loop iteration

# Remember to select the list of element with [[]]; otherwise, you are selecting the component i.e. primes$component

# Paste
# paste will concatonate strings
# e.g.: paste(month.abb, "is the", nth, "month of the year.") will print
# 'Jan is the 1st month of the year.' when nth is '1st' or a vector of '1st','2nd', etc. & month.abb contains a collection of abbreviated months

# Function documentation:
# help(foo)
# ?foo

# Mean
# mean(x, trim= 0.2, na.rm= TRUE) # trim will set the number of decimal places; na.rm = TRUE will remove any NA values from x and calculate the mean; trim & na.rm are optional values

# Absolute value
# abs() will use the absolute value of any integer

# Mean absolute value
# mean(abs(x - y), na.rm=TRUE) # This will remove all NA values, take the absolute value of the difference between x & y, and take the mean of the differences when x & y are a collection of values

# Functions
# the order of the function inputs does not matter so long as the input name is specified.
# The function will return the last line of code if there is no return() statement in the function
# The return() function will return a value and will discontinue the function similar to a break() statement

# Writing functions:
# creating a function is similar to creating a function pointer in c:
# function_name <- function(arg1, arg2){ body }
# functions can be declared with no arguments; i.e. function() etc...

# Function scope:
# variables included inside a function do not have global scope

# Variables are passed by value not by reference; This means that a variable that is passed into a function an altered is not updated unless explicitly assigned to the new value outside of the function; i.e.: count <- new_count_value(count) # this will update count; new_count_value(count){count <- count +1; return(count)}; This will return count + 1, but the initial value of count declared outside the function will remain unchanged.

# R packages:
# CRAN: Comprehensive R Archive Network: this is the archive repository where all R packages are located
# basic: this includes mean(), abs(), & sample(); this is the basic package
# ggvis: This is the package that enables plot visualization; This is not included by default

# Install R packages:
# To install R packages, use the function: install.packages("ggvis")

# Finding R packages that are installed:
# use search()

# Load packages 
# After installing a package, load the package using library()
# require() will throw a warning rather than an error if a package is not installed

# Double quotes are optional when defining packages to load: i.e. library(rjson) or library("rjson") will both work; The same is true with require("rjson") & require(rjson)

# lapply
# The lapply function will take an argument, x, and a function, foo, and apply foo to the left argument, x, where "x" is a vector. 
# To apply multiple arguments to a vector, call:
# lapply(vector, foo, foo_argument)

# Anonymous functions
# Anonymous functions are similar to lambda functions; To use anonymous functions, literally declare them as follows:
# function(x) { 3*x }

# unlist: This will map a list to a vector; list() always returns a list

# sapply: This will use lapply and unlist all at once; set USE.NAMES = FALSE to not use names when returning the value of sapply ( this will return only the vector). Sapply tries to SIMPLIFY a list to an array.

# Comparing two vectors with the identical() function

# vapply: 
# similar to sapply, vapply will map a function to a vector. vapply takes a return type as a mandatory argument.

# Utilities
#seq(): Generate sequences, by specifying the from, to, and by arguments.
#rep(): Replicate elements of vectors and lists.
#sort(): Sort a vector in ascending order. Works on numerics, but also on #character strings and logicals.
#rev(): Reverse the elements in a data structures for which reversal is defined.
#str(): Display the structure of any R object.
#append(): Merge vectors or lists.
#is.*(): Check for the class of an R object.
#as.*(): Convert an R object from one class to another.
#unlist(): Flatten (possibly embedded) lists to produce a vector.

# Grep
# grepl: Returns true when a pattern is found in a character string
# grep: returns a vector of indices that contain the pattern 

# Regex:
# . : "." matches anycharacter
# * : "*" matches zero or more times
# \\ : "\\" escapes metacharacters to literally mean the character. i.e.: \\$ literally is interpreted to $.
# $ : marks the end of a string. i.e.: d$ will search for words ending in "d".
# ^ : marks the beginning of a string. i.e.: ^s will search for words beginning with "s".
# \\s : match a space
# [] : match a group
# + : match 1 or more times
# [0-9]+ : match a number 1 or more times
# () : used to define replacement.
# sub()
# substitute replace a part of a string with another string.
# () will set a variable for replacement into the position of \\1; 
# E.G. : sub(".*\\s([0-9]+)\\snomination.*$", "\\1", awards)
# awards <- "1 win and 2 nominations."
# therefore 2 nominations will match, the 2 will be captured, and the string will be substituted by what is captured.


