# Measure of spread
# seq(): creates a sequence of numbers 

# quantile(): calcultes the quantiles of a spread of numbers
# Define how split the quantiles using probs = c(0, 0.2, 0.4, 0.6, 0.8, 1)
# Example
# quantile(food_consumption$co2_emission, probs = c(0, 0.2, 0.4, 0.6, 0.8, 1))
# quantile(food_consumption$co2_emission, seq(0,1,.1)) # sequence will create the quantiles here;

# Variance
# var(): this function is used to calculate the variance

# Standard deviation
# sd(): this function is used to calculate the standard deviation 

# The IQR is calculated by the first and third quartile ranges
# Calculate total co2_emission per country: emissions_by_country

# Example
# emissions_by_country <- food_consumption %>%
#  group_by(country) %>%
#  summarize(total_emission = sum(co2_emission))

# Compute the first and third quartiles and IQR of total_emission
# q3 <- quantile(emissions_by_country$total_emission, 0.75)
# q1 <- quantile(emissions_by_country$total_emission, 0.25)
# iqr <- q3 - q1

# sample
# sample_n(1) : this will choose 1 sample randomly; it is used with a pipe; 
# Example use:
# data %>% sample_n(1)

# set_seed(5) will set the seed so the same data will be pulled everytime from the data;
# sampling without replacement; taking a sample without replacing the sample in the dataset;

# sample with replacement:
# sample_n(5, replace = TRUE)

```{r}
?punif # probability density function

# The sales software used at your company is set to automatically back itself up, but no one knows exactly what time the back-ups happen. It is known, however, that back-ups happen exactly every 30 minutes. Amir comes back from sales meetings at random times to update the data on the client he just met with. He wants to know how long he'll have to wait for his newly-entered data to get backed up. Use your new knowledge of continuous uniform distributions to model this situation and answer Amir's questions.

punif()
```