# Linear regression
# A linear regression is the simplest of machine learning models; It is used to make a prediction on the future expected value given a historical set of data. 

# unemployment is available
summary(unemployment)

# Define a formula to express female_unemployment as a function of male_unemployment
fmla <- female_unemployment ~ male_unemployment

# Print it
fmla

# Use the formula to fit a model: unemployment_model
unemployment_model <-  lm(fmla, data = unemployment)

# Print it 
unemployment_model

#####

# prediction 
# unemployment is available
summary(unemployment)

# newrates is available
newrates

# Predict female unemployment in the unemployment dataset
unemployment$prediction <-  predict(unemployment_model)

# Load the ggplot2 package
library(ggplot2)

# Make a plot to compare predictions to actual (prediction on x axis)
ggplot(unemployment, aes(x = prediction, y = female_unemployment)) + 
  geom_point() +
  geom_abline(color = "blue")

# Predict female unemployment rate when male unemployment is 5%
pred <- predict(unemployment_model, newdata = newrates)
pred

#####

# Multivariate linear regression: 
# It is possible to include multiple variables in the model that is used to predict.

# bloodpressure is available
summary(bloodpressure)

# Create the formula and print it
fmla <- blood_pressure ~ age + weight
fmla

# Fit the model: bloodpressure_model
bloodpressure_model <- lm(fmla, data = bloodpressure)

# Print bloodpressure_model and call summary()
bloodpressure_model
summary(bloodpressure_model)

######

# geom_pointrange(aes(ymin = 0, ymax = residuals)): This function will create a line connecting the points; This is useful to connect the horizontal x axis to a scatterplot of points
# geom_hline(yintercept = 0, linetype = 3): This function will create a horizontal line at the x-axis; linetype is the thickness of the line. 

# Gain Curve Plot
# # unemployment (with predictions) is available
# summary(unemployment)

# unemployment_model is available
# summary(unemployment_model)

# Load the package WVPlots
# library(WVPlots)

# Plot the Gain Curve
# GainCurvePlot(unemployment, "predictions", "female_unemployment", "Unemployment model")

# root mean square error (RMSE): this is a metric which will detect the accuracy of your model
# Calculte the RMSE with (rmse <- sqrt(mean(res^2)))

# standard deviation
# sd()

# R^2: a metric of how well a model fits the data.
# values range from 0 to 1
# a value of 1 indicates a model fits well. 
# a value of 0 indicates the prediction is no better than guessing the average value